#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkaitmeninisTreneris
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PratimuDataBase")]
	public partial class PratimuKatalogasDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPratimai(Pratimai instance);
    partial void UpdatePratimai(Pratimai instance);
    partial void DeletePratimai(Pratimai instance);
    #endregion
		
		public PratimuKatalogasDataContext() : 
				base(global::SkaitmeninisTreneris.Properties.Settings.Default.PratimuDataBaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PratimuKatalogasDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PratimuKatalogasDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PratimuKatalogasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PratimuKatalogasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Pratimai> Pratimais
		{
			get
			{
				return this.GetTable<Pratimai>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pratimai")]
	public partial class Pratimai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _MuscleGroup;
		
		private string _MuscleGroupPhoto;
		
		private string _ExerciseName;
		
		private string _MainMuscle;
		
		private string _ExtraMuscles;
		
		private string _Tools;
		
		private System.Nullable<float> _Weight;
		
		private string _Photo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMuscleGroupChanging(string value);
    partial void OnMuscleGroupChanged();
    partial void OnMuscleGroupPhotoChanging(string value);
    partial void OnMuscleGroupPhotoChanged();
    partial void OnExerciseNameChanging(string value);
    partial void OnExerciseNameChanged();
    partial void OnMainMuscleChanging(string value);
    partial void OnMainMuscleChanged();
    partial void OnExtraMusclesChanging(string value);
    partial void OnExtraMusclesChanged();
    partial void OnToolsChanging(string value);
    partial void OnToolsChanged();
    partial void OnWeightChanging(System.Nullable<float> value);
    partial void OnWeightChanged();
    partial void OnPhotoChanging(string value);
    partial void OnPhotoChanged();
    #endregion
		
		public Pratimai()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MuscleGroup", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MuscleGroup
		{
			get
			{
				return this._MuscleGroup;
			}
			set
			{
				if ((this._MuscleGroup != value))
				{
					this.OnMuscleGroupChanging(value);
					this.SendPropertyChanging();
					this._MuscleGroup = value;
					this.SendPropertyChanged("MuscleGroup");
					this.OnMuscleGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MuscleGroupPhoto", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MuscleGroupPhoto
		{
			get
			{
				return this._MuscleGroupPhoto;
			}
			set
			{
				if ((this._MuscleGroupPhoto != value))
				{
					this.OnMuscleGroupPhotoChanging(value);
					this.SendPropertyChanging();
					this._MuscleGroupPhoto = value;
					this.SendPropertyChanged("MuscleGroupPhoto");
					this.OnMuscleGroupPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExerciseName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ExerciseName
		{
			get
			{
				return this._ExerciseName;
			}
			set
			{
				if ((this._ExerciseName != value))
				{
					this.OnExerciseNameChanging(value);
					this.SendPropertyChanging();
					this._ExerciseName = value;
					this.SendPropertyChanged("ExerciseName");
					this.OnExerciseNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainMuscle", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MainMuscle
		{
			get
			{
				return this._MainMuscle;
			}
			set
			{
				if ((this._MainMuscle != value))
				{
					this.OnMainMuscleChanging(value);
					this.SendPropertyChanging();
					this._MainMuscle = value;
					this.SendPropertyChanged("MainMuscle");
					this.OnMainMuscleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtraMuscles", DbType="NVarChar(MAX)")]
		public string ExtraMuscles
		{
			get
			{
				return this._ExtraMuscles;
			}
			set
			{
				if ((this._ExtraMuscles != value))
				{
					this.OnExtraMusclesChanging(value);
					this.SendPropertyChanging();
					this._ExtraMuscles = value;
					this.SendPropertyChanged("ExtraMuscles");
					this.OnExtraMusclesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tools", DbType="NVarChar(MAX)")]
		public string Tools
		{
			get
			{
				return this._Tools;
			}
			set
			{
				if ((this._Tools != value))
				{
					this.OnToolsChanging(value);
					this.SendPropertyChanging();
					this._Tools = value;
					this.SendPropertyChanged("Tools");
					this.OnToolsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Real")]
		public System.Nullable<float> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this.OnPhotoChanging(value);
					this.SendPropertyChanging();
					this._Photo = value;
					this.SendPropertyChanged("Photo");
					this.OnPhotoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
