<?xml version="1.0" encoding="utf-8"?><Database Name="Pratimai" Class="PratimuKatalogasLINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Pratimai.mdf;Integrated Security=True" SettingsObjectName="SkaitmeninisTreneris.Properties.Settings" SettingsPropertyName="PratimaiConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DienosPlanas" Member="DienosPlanas">
    <Type Name="DienosPlana">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Day" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExerciseName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Tools" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PratimaiTable" Member="PratimaiTables">
    <Type Name="PratimaiTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RaumenuGrupesId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExerciseName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="MainMuscle" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ExtraMuscles" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Tools" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Weight" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="Photo" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Patinka" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="RaumenuGrupe_PratimaiTable" Member="RaumenuGrupe" ThisKey="RaumenuGrupesId" OtherKey="Id" Type="RaumenuGrupe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RaumenuGrupes" Member="RaumenuGrupes">
    <Type Name="RaumenuGrupe">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UsersId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MuscleGroup" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="MuscleGroupPhoto" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="RaumenuGrupe_PratimaiTable" Member="PratimaiTables" ThisKey="Id" OtherKey="RaumenuGrupesId" Type="PratimaiTable" />
      <Association Name="Table_RaumenuGrupe" Member="Table" ThisKey="UsersId" OtherKey="Id" Type="Table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Table]" Member="Tables">
    <Type Name="Table">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ZmogausId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Table_RaumenuGrupe" Member="RaumenuGrupes" ThisKey="Id" OtherKey="UsersId" Type="RaumenuGrupe" />
      <Association Name="User_Table" Member="User" ThisKey="ZmogausId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="User_Table" Member="Tables" ThisKey="Id" OtherKey="ZmogausId" Type="Table" />
    </Type>
  </Table>
</Database>